version: '3.5'
networks:
  trustblock-test-network: {}
services:
  db:
    container_name: trustblock-test-db
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: '%'
    networks:
      - trustblock-test-network
  api:
    container_name: trustblock-test-api
    build:
      context: ./server
    environment:
      PORT: 3000
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
    ports:
      - 3000:3000
    command: >
      npm run start:dev
    networks:
      - trustblock-test-network
