version: '3.5'
networks:
  trustblock-test-network: {}
services:
  db:
    container_name: trustblock-test-db
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: trustblock
      MYSQL_USER: roy
      MYSQL_PASSWORD: royroy
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    networks:
      - trustblock-test-network
  api:
    container_name: trustblock-test-api
    build:
      context: ./server
    environment:
      PORT: 3000
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - 3000:3000
    command: >
      npm run start:dev
    networks:
      - trustblock-test-network
  client:
    container_name: trustblock-test-client
    build:
      context: ./client
    command: >
      npm run dev
    ports:
      - 5173:5173
    networks:
      - trustblock-test-network
